### ISSUE TITLE
Problem in IvMatrix44::Transpose

### ISSUE THREAD

**Issue by leonsal** [jvanverth/essentialmath#56]
Hi,

In IvMatrix44::Transpose line 352 should be:
`mV[3] = mV[12]` instead of `mV[2] = mV[12]`

(https://github.com/jvanverth/essentialmath/blob/master/src/common/IvMath/IvMatrix44.cpp)

Regards.

**Comment by jvanverth** [comment]
Thanks, I'll patch that this weekend.
