### ISSUE TITLE
Possible error in IvMatrix44 rotation with axis angle

### ISSUE THREAD

**Issue by cbaggers** [jvanverth/essentialmath#57]
https://github.com/jvanverth/essentialmath/blob/master/src/common/IvMath/IvMatrix44.cpp#L575
```
float txy = tx*nAxis.y; float tyz = tx*nAxis.z; float txz = tx*nAxis.z;
```
this line looks suspect in that `tyz` and `txz` both equal `tx*nAxis.z` 

Should it be `float tyz = ty*nAxis.z` or, as there is no further mutation, could we combine the values?

**Comment by jvanverth** [comment]
Yes, it should be float txy = tx*nAxis.y; float tyz = ty*nAxis.z;

**Comment by cbaggers** [comment]
Thanks!
