### ISSUE TITLE
Use of undeclared identifier getpid in lvDebugger.cpp

### ISSUE THREAD

**Issue by erikmartinessanches** [jvanverth/essentialmath#59]
I'm new and trying to set up on MacOsX with this error:
![image](https://user-images.githubusercontent.com/4912935/58752500-038a0c00-84b0-11e9-9f97-6aa8f9cdcb52.png)

**Comment by jvanverth** [comment]
Thanks for the push -- I've been meaning to fix that for a while now.

**Comment by jvanverth** [comment]
(Fixed by https://github.com/jvanverth/essentialmath/commit/7b46e67bec39999935e3470dfdb7ffc98611fbf9)

**Comment by erikmartinessanches** [comment]
Wow an author who fixed his code, amazing.
